//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicBookGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int id_venta { get; set; }
        public int cantidad { get; set; }
        public int id_comic { get; set; }
        public decimal valor { get; set; }
        public System.DateTime fecha_venta { get; set; }
    
        public virtual comic comic { get; set; }
    }
}
